# Generated by Django 3.2.5 on 2021-09-19 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todolist", "0002_alter_task_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="id",
            new_name="uu_id",
        ),
    ]
